In [1]:
import numpy as np

In [2]:
arreglo_grados = np.array([0, 30, 45, 60, 90])

In [3]:
arreglo_radianes = arreglo_grados * np.pi / 180

In [4]:
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [7]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [31]:
numero_random = np.random.randint(
    11 #[0, [11
)

numero_random

6

In [42]:
numero_random_negativo = np.random.randint(
    -9,2
)

numero_random_negativo

-9

In [60]:
arreglo_random = np.random.randint(

    10,
    20,
    8
    
)
arreglo_random

array([15, 16, 10, 13, 15, 12, 13, 14])

In [57]:
np.random.rand(27)

np.random.rand(3,3,4) #se puede mandar el SHAPE como parametro

array([[[0.78774799, 0.16172318, 0.54786663, 0.49255207],
        [0.86647223, 0.07870482, 0.38083626, 0.91299039],
        [0.1534393 , 0.58030171, 0.68359334, 0.50538461]],

       [[0.7645199 , 0.46010801, 0.88968937, 0.53747213],
        [0.98943438, 0.45252697, 0.49134358, 0.40515351],
        [0.82747107, 0.8827953 , 0.78213488, 0.19116454]],

       [[0.34042564, 0.52500793, 0.95647156, 0.22655784],
        [0.89999688, 0.63959846, 0.48608464, 0.01561858],
        [0.55624651, 0.84696018, 0.82204954, 0.51704708]]])

In [62]:
np.average(arreglo_random)

13.5

In [63]:
np.mean(arreglo_random)

13.5

In [64]:
np.median(arreglo_random)

13.5

In [65]:
np.std(arreglo_random)

1.8027756377319946

In [66]:
np.var(arreglo_random)

3.25

In [67]:
arreglo_random.mean()

13.5